// Generated by gencpp from file agcar_ctrl_msg/agcar_ctrl.msg
// DO NOT EDIT!


#ifndef AGCAR_CTRL_MSG_MESSAGE_AGCAR_CTRL_H
#define AGCAR_CTRL_MSG_MESSAGE_AGCAR_CTRL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace agcar_ctrl_msg
{
template <class ContainerAllocator>
struct agcar_ctrl_
{
  typedef agcar_ctrl_<ContainerAllocator> Type;

  agcar_ctrl_()
    : vx(0.0)
    , wz(0.0)  {
    }
  agcar_ctrl_(const ContainerAllocator& _alloc)
    : vx(0.0)
    , wz(0.0)  {
  (void)_alloc;
    }



   typedef float _vx_type;
  _vx_type vx;

   typedef float _wz_type;
  _wz_type wz;





  typedef boost::shared_ptr< ::agcar_ctrl_msg::agcar_ctrl_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::agcar_ctrl_msg::agcar_ctrl_<ContainerAllocator> const> ConstPtr;

}; // struct agcar_ctrl_

typedef ::agcar_ctrl_msg::agcar_ctrl_<std::allocator<void> > agcar_ctrl;

typedef boost::shared_ptr< ::agcar_ctrl_msg::agcar_ctrl > agcar_ctrlPtr;
typedef boost::shared_ptr< ::agcar_ctrl_msg::agcar_ctrl const> agcar_ctrlConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::agcar_ctrl_msg::agcar_ctrl_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::agcar_ctrl_msg::agcar_ctrl_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::agcar_ctrl_msg::agcar_ctrl_<ContainerAllocator1> & lhs, const ::agcar_ctrl_msg::agcar_ctrl_<ContainerAllocator2> & rhs)
{
  return lhs.vx == rhs.vx &&
    lhs.wz == rhs.wz;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::agcar_ctrl_msg::agcar_ctrl_<ContainerAllocator1> & lhs, const ::agcar_ctrl_msg::agcar_ctrl_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace agcar_ctrl_msg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::agcar_ctrl_msg::agcar_ctrl_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::agcar_ctrl_msg::agcar_ctrl_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::agcar_ctrl_msg::agcar_ctrl_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::agcar_ctrl_msg::agcar_ctrl_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::agcar_ctrl_msg::agcar_ctrl_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::agcar_ctrl_msg::agcar_ctrl_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::agcar_ctrl_msg::agcar_ctrl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "de1cd4fda7405bb38c76048f91112711";
  }

  static const char* value(const ::agcar_ctrl_msg::agcar_ctrl_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xde1cd4fda7405bb3ULL;
  static const uint64_t static_value2 = 0x8c76048f91112711ULL;
};

template<class ContainerAllocator>
struct DataType< ::agcar_ctrl_msg::agcar_ctrl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "agcar_ctrl_msg/agcar_ctrl";
  }

  static const char* value(const ::agcar_ctrl_msg::agcar_ctrl_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::agcar_ctrl_msg::agcar_ctrl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 vx\n"
"float32 wz\n"
;
  }

  static const char* value(const ::agcar_ctrl_msg::agcar_ctrl_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::agcar_ctrl_msg::agcar_ctrl_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.vx);
      stream.next(m.wz);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct agcar_ctrl_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::agcar_ctrl_msg::agcar_ctrl_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::agcar_ctrl_msg::agcar_ctrl_<ContainerAllocator>& v)
  {
    s << indent << "vx: ";
    Printer<float>::stream(s, indent + "  ", v.vx);
    s << indent << "wz: ";
    Printer<float>::stream(s, indent + "  ", v.wz);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AGCAR_CTRL_MSG_MESSAGE_AGCAR_CTRL_H
